export const SET_AUTH_LOADING = "SET_AUTH_LOADING"
export const SET_AUTH_STATUS = "SET_AUTH_STATUS"
export const SET_AUTH_ERROR = "SET_AUTH_ERROR"
export const SET_AUTH_USER = "SET_AUTH_USER"

export const SET_REQUEST_BODY = "SET_REQUEST_BODY"
export const SET_REQUEST_ERROR = "SET_REQUEST_ERROR"

export const SET_RESPONSE_BODY = "SET_RESPONSE_BODY"
export const SET_RESPONSE_ERROR = "SET_RESPONSE_ERROR"

export const SET_FETCH_LOADING = "SET_FETCH_LOADING"
export const SET_FETCH_SUCCESS = "SET_FETCH_SUCCESS"
export const SET_FETCH_ERROR = "SET_FETCH_ERROR"
